### ISSUE TITLE
Split helm-chart-with-parameters into three exercises

### ISSUE THREAD

**Issue by zanderhavgaard** [eficode-academy/helm-katas#18]
first exercise should be about values
second about pipelines
third about functions

each exercise should build upon the previous

**Comment by sofusalbertsen** [comment]
Should wait till #14 gets pulled

**Comment by zanderhavgaard** [comment]
#14 has been merged, will now start working on this.

**Comment by zanderhavgaard** [comment]
Fixed in #23
